development:
  adapter: postgresql
  encoding: unicode
  database: sentiMatchRails_dev
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: sentiMatchRails_test
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: sentiMatchRails_test
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  min_messages: warning
